import {prepareUpload,completeUpload} from '@/lib/cloud-upload';
import {siteUrl} from '@/lib/site-url';
import {NextRequest,NextResponse} from 'next/server';
import {getUser,authenticate,logout,records,addLead,addProperty,setContractStatus,addDocument,downloadDocument,listSharedResources,addSharedResource,changePassword,local} from '@/lib/store';
import {authSchema,leadSchema,propertySchema,memberPropertySchema,contractStatusSchema} from '@/lib/validation';
export const runtime='nodejs';export const dynamic='force-dynamic';
const limits=new Map<string,{count:number;until:number}>();
function rate(req:NextRequest,scope:string,max:number){const now=Date.now();for(const[k,v]of limits)if(v.until<now)limits.delete(k);const key=scope+':'+(local?'local':req.headers.get('x-forwarded-for')?.split(',')[0]||'unknown');let v=limits.get(key);if(!v){v={count:0,until:now+900000};limits.set(key,v)}return ++v.count<=max}
const json=(v:unknown,status=200)=>NextResponse.json(v,{status,headers:{'Cache-Control':'no-store'}});
async function handler(req:NextRequest,{params}:{params:Promise<{route:string[]}>}){const {route}=await params;const action=route.join('/');const token=req.cookies.get('sr-session')?.value;try{
if(req.method==='POST'){const origin=req.headers.get('origin');const expected=siteUrl();const allowed=process.env.NODE_ENV!=='production'&&local?['http://127.0.0.1:3000','http://localhost:3000']:[expected];if(!origin||!allowed.includes(origin))return json({error:'Invalid origin'},403);if(Number(req.headers.get('content-length')||0)>11*1024*1024)return json({error:'Request too large'},413)}
if(action==='config'&&req.method==='GET')return json({local});
if(action==='leads'&&req.method==='POST'){if(!rate(req,'leads',15))return json({error:'Please try again later'},429);const raw=await req.text();if(raw.length>20000)return json({error:'Request too large'},413);const parsed=leadSchema.safeParse(JSON.parse(raw));if(!parsed.success)return json({error:'Invalid form data'},400);const {website,consent,...data}=parsed.data;if(data.kind==='evaluation'&&!await getUser(token))return json({error:'Membership sign-in required'},401);return json(await addLead(data),201)}
if((action==='auth/register'||action==='auth/login')&&req.method==='POST'){if(!rate(req,'auth',30))return json({error:'Please try again later'},429);const parsed=authSchema.safeParse(await req.json());if(!parsed.success)return json({error:'Invalid credentials'},400);const {email,password,name,confirmPassword}=parsed.data;if(action==='auth/register'&&(!name||password.length<8||confirmPassword!==password))return json({error:'Name and matching passwords of at least 8 characters required'},400);const result=await authenticate(email,password,action==='auth/register'?name:undefined);const response=json({role:result.user?.role,confirm:'confirm' in result ? result.confirm : false});if(result.token)response.cookies.set('sr-session',result.token,{httpOnly:true,secure:process.env.NODE_ENV==='production'||req.nextUrl.protocol==='https:',sameSite:'lax',path:'/',maxAge:('expiresIn' in result?result.expiresIn:8*60*60)});return response}
if(action==='auth/logout'&&req.method==='POST'){if(token)await logout(token);const r=json({ok:true});r.cookies.set('sr-session','',{httpOnly:true,sameSite:'lax',path:'/',maxAge:0});return r}
const user=await getUser(token);if(!user)return json({error:'Authentication required'},401);
if(action==='member-resources'&&req.method==='GET')return json(await listSharedResources(token));
if(action==='auth/password'&&req.method==='POST'){if(!rate(req,'password',10))return json({error:'Please try again later'},429);const body=await req.json();if(typeof body.currentPassword!=='string'||body.currentPassword.length>128||typeof body.password!=='string'||body.password.length<8||body.password.length>128||body.confirmPassword!==body.password)return json({error:'Matching passwords of at least 8 characters required'},400);await changePassword(user,body.currentPassword,body.password,token!);return json({ok:true})}
if(action==='workspace'&&req.method==='GET')return json({...await records(user,token),local});
if(route[0]==='documents'&&route.length===2&&req.method==='GET'){if(!/^[a-f0-9-]{36}$/.test(route[1]))return json({error:'Not found'},404);const result=await downloadDocument(user,route[1],token);if(!result)return json({error:'Not found'},404);if('url' in result)return NextResponse.redirect(result.url!,{status:303,headers:{'Cache-Control':'private, no-store'}});return new NextResponse(new Uint8Array(result.bytes),{headers:{'Content-Type':'application/octet-stream','Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(result.doc.filename),'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}})}
if(action==='properties'&&req.method==='POST'){const parsed=memberPropertySchema.safeParse(await req.json());if(!parsed.success)return json({error:'Property name and address required'},400);return json(await addProperty({...parsed.data,owner_id:user.id,strategy:'undecided',status:'review',bedrooms:null,notes:'',contract_status:'unsigned'},token),201)}
if(user.role!=='admin')return json({error:'Administrator access required'},403);
if(action==='admin/uploads/prepare'&&req.method==='POST'&&!local)return json(await prepareUpload(user,token!,await req.json()));
if(action==='admin/uploads/complete'&&req.method==='POST'&&!local)return json(await completeUpload(user,token!,(await req.json()).ticket),201);
if(!local&&['admin/documents','admin/member-resources'].includes(action))return json({error:'Use direct storage upload'},400);
if(action==='admin/property-contract'&&req.method==='POST'){const parsed=contractStatusSchema.safeParse(await req.json());if(!parsed.success)return json({error:'Invalid contract status'},400);const property=await setContractStatus(parsed.data.property_id,parsed.data.contract_status,token);return property?json(property):json({error:'Property not found'},404)}
if(action==='admin/member-resources'&&req.method==='POST'){const f=await req.formData();const file=f.get('file');const title=String(f.get('title')||'').trim();const titleEn=String(f.get('title_en')||'').trim()||title;const description=String(f.get('description')||'').trim();const descriptionEn=String(f.get('description_en')||'').trim()||description;if(!(file instanceof File)||!title||title.length>200||titleEn.length>200||description.length>2000||descriptionEn.length>2000||file.size===0||file.size>10*1024*1024||!/[.](pdf|docx|xlsx|csv|txt|png|jpe?g)$/i.test(file.name))return json({error:'Invalid resource or file'},400);return json(await addSharedResource({title:[titleEn,title],description:[descriptionEn,description],filename:file.name.replace(/[^\p{L}\p{N} ._-]/gu,'_').slice(0,200),mime:'application/octet-stream'},Buffer.from(await file.arrayBuffer())),201)}
if(action==='admin/properties'&&req.method==='POST'){const parsed=propertySchema.safeParse(await req.json());if(!parsed.success)return json({error:'Invalid property data'},400);return json(await addProperty(parsed.data,token),201)}
if(action==='admin/documents'&&req.method==='POST'){const f=await req.formData();const file=f.get('file');const title=String(f.get('title')||'').trim();const owner_id=String(f.get('owner_id')||'');const property_id=String(f.get('property_id')||'')||null;if(!(file instanceof File)||!title||title.length>200||!/^[a-f0-9-]{36}$/.test(owner_id)||property_id&&!/^[a-f0-9-]{36}$/.test(property_id))return json({error:'Invalid document data'},400);if(file.size>10*1024*1024||file.size===0)return json({error:'File must be between 1 byte and 10 MB'},400);if(!/\.(pdf|docx|xlsx|csv|txt|png|jpe?g)$/i.test(file.name))return json({error:'Unsupported file type'},400);return json(await addDocument({owner_id,property_id,title,filename:file.name.replace(/[^\p{L}\p{N} ._-]/gu,'_').slice(0,200),mime:file.type||'application/octet-stream',size:file.size},Buffer.from(await file.arrayBuffer())),201)}
return json({error:'Not found'},404)
}catch(error){console.error('Request failed:',error instanceof Error?error.message:'unknown');return json({error:'Request could not be completed'},400)}}
export const GET=handler;export const POST=handler;


