import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const base='http://127.0.0.1:3000';const prefix='mvp-test-'+Date.now();const password='Test-123';const tracked={users:[],documents:[],leads:[],properties:[],sessions:[]};
async function request(path,{method='GET',body,cookie,origin=base}={}){const headers={};if(method==='POST')headers.Origin=origin;if(cookie)headers.Cookie=cookie;if(body&&!(body instanceof FormData))headers['Content-Type']='application/json';return fetch(base+'/api/'+path,{method,headers,body:body instanceof FormData?body:body?JSON.stringify(body):undefined})}
async function account(label){const email=prefix+'-'+label+'@example.test';const r=await request('auth/register',{method:'POST',body:{name:'MVP test '+label,email,password,confirmPassword:password}});assert.equal(r.status,200);const cookie=r.headers.get('set-cookie').split(';')[0];const d=await(await request('workspace',{cookie})).json();tracked.users.push(d.user.id);return {cookie,user:d.user}}
test('Local MVP functional and isolation checks',async t=>{const config=await(await request('config')).json();assert.equal(config.local,true,'Never run these tests against cloud data');const before=JSON.parse(await fs.readFile('.data/store.json','utf8'));let a,b,admin;
try{
await t.test('private workspace rejects anonymous access',async()=>assert.equal((await request('workspace')).status,401));
await t.test('cross-origin writes are rejected',async()=>assert.equal((await request('auth/login',{method:'POST',origin:'https://untrusted.example',body:{email:'x@example.com',password}})).status,403));
await t.test('registration validates password and prevents admin self-enrollment',async()=>{assert.equal((await request('auth/register',{method:'POST',body:{name:'test',email:'weak@example.test',password:'weak'}})).status,400);assert.equal((await request('auth/register',{method:'POST',body:{name:'test',email:'agentkelly2024@gmail.com',password,confirmPassword:password}})).status,400)});
await t.test('missing and mismatched confirmation rejected',async()=>{for(const confirmPassword of [undefined,'Different'])assert.equal((await request('auth/register',{method:'POST',body:{name:'Test',email:prefix+'-mismatch@example.test',password,confirmPassword}})).status,400)});
await t.test('owners register with private sessions',async()=>{a=await account('one');b=await account('two');assert.equal(a.user.role,'owner');assert.equal((await request('workspace',{cookie:a.cookie})).status,200)});
await t.test('wrong password rejected and owner cannot administer',async()=>{assert.equal((await request('auth/login',{method:'POST',body:{email:a.user.email,password:'not-the-password'}})).status,400);assert.equal((await request('admin/properties',{method:'POST',cookie:a.cookie,body:{}})).status,403)});
await t.test('admin login',async()=>{const fixture=await account('admin');const db=JSON.parse(await fs.readFile('.data/store.json','utf8'));db.users.find(u=>u.id===fixture.user.id).role='admin';await fs.writeFile('.data/store.json',JSON.stringify(db,null,2));const r=await request('auth/login',{method:'POST',body:{email:fixture.user.email,password}});assert.equal(r.status,200);assert.equal((await r.json()).role,'admin');admin=r.headers.get('set-cookie').split(';')[0]});
await t.test('admin assigns property and it is visible only to its owner',async()=>{const r=await request('admin/properties',{method:'POST',cookie:admin,body:{owner_id:a.user.id,title:prefix,address:'Test address - not a real property',strategy:'co-living',status:'review',bedrooms:4,notes:'Test note'}});assert.equal(r.status,201);const p=await r.json();tracked.properties.push(p.id);const av=await(await request('workspace',{cookie:a.cookie})).json();const bv=await(await request('workspace',{cookie:b.cookie})).json();assert.equal(av.properties.length,1);assert.equal(bv.properties.length,0);assert.equal(av.leads.length,0);assert.equal(av.owners.length,0)});
await t.test('members add private unsigned properties and only admin changes contract status',async()=>{const body={title:prefix+' self-added',address:'Member test address'};assert.equal((await request('properties',{method:'POST',body})).status,401);for(const extra of [{owner_id:b.user.id},{contract_status:'signed'}])assert.equal((await request('properties',{method:'POST',cookie:a.cookie,body:{...body,...extra}})).status,400);assert.equal((await request('properties',{method:'POST',cookie:a.cookie,body:{title:' ',address:'x'}})).status,400);const r=await request('properties',{method:'POST',cookie:a.cookie,body});assert.equal(r.status,201);const p=await r.json();tracked.properties.push(p.id);assert.equal(p.owner_id,a.user.id);assert.equal(p.contract_status,'unsigned');assert.equal(p.bedrooms,null);const change={property_id:p.id,contract_status:'signed'};assert.equal((await request('admin/property-contract',{method:'POST',cookie:a.cookie,body:change})).status,403);assert.equal((await request('admin/property-contract',{method:'POST',cookie:admin,body:change})).status,200);const av=await(await request('workspace',{cookie:a.cookie})).json();assert.equal(av.properties.find(v=>v.id===p.id).contract_status,'signed');const bv=await(await request('workspace',{cookie:b.cookie})).json();assert.equal(bv.properties.length,0);const saved=JSON.parse(await fs.readFile('.data/store.json','utf8'));assert.equal(saved.properties.find(v=>v.id===p.id).contract_status,'signed')});
await t.test('private upload/download and cross-owner denial',async()=>{const f=new FormData();f.set('owner_id',a.user.id);f.set('property_id',tracked.properties[0]);f.set('title',prefix);f.set('file',new Blob(['private-test-document'],{type:'text/plain'}),'test.txt');const r=await request('admin/documents',{method:'POST',cookie:admin,body:f});assert.equal(r.status,201);const d=await r.json();tracked.documents.push(d.id);const download=await request('documents/'+d.id,{cookie:a.cookie});assert.equal(download.status,200);assert.equal(await download.text(),'private-test-document');assert.equal((await request('documents/'+d.id,{cookie:b.cookie})).status,404);assert.equal((await request('documents/'+d.id)).status,401)});
await t.test('mismatched owner/property upload rejected',async()=>{const f=new FormData();f.set('owner_id',b.user.id);f.set('property_id',tracked.properties[0]);f.set('title',prefix);f.set('file',new Blob(['test']), 'test.txt');assert.equal((await request('admin/documents',{method:'POST',cookie:admin,body:f})).status,400)});
await t.test('contact and Chinese evaluation save with truthful email status',async()=>{const bodies=[{kind:'contact',name:prefix,email:a.user.email,message:'Test inquiry',language:'en',consent:'on',website:''},{kind:'evaluation',firstName:'测试',lastName:'业主',email:a.user.email,phone:'1234567890',address:'Test only',city:'Savannah',state:'GA',zip:'31401',bedrooms:3,bathrooms:2,status:'vacant',interest:'co-living',rent:'',message:'测试评估',language:'zh',consent:'on',website:''}];for(const body of bodies){if(body.kind==='evaluation')assert.equal((await request('leads',{method:'POST',body})).status,401);const r=await request('leads',{method:'POST',body,cookie:body.kind==='evaluation'?a.cookie:undefined});assert.equal(r.status,201);const d=await r.json();tracked.leads.push(d.id);assert.equal(d.notification,'pending')}const db=JSON.parse(await fs.readFile('.data/store.json','utf8'));assert.ok(tracked.leads.every(id=>db.leads.some(l=>l.id===id)));const ad=await(await request('workspace',{cookie:admin})).json();assert.ok(tracked.leads.every(id=>ad.leads.some(l=>l.id===id)))});
await t.test('invalid form and bot honeypot rejected',async()=>{assert.equal((await request('leads',{method:'POST',body:{kind:'contact',email:'bad'}})).status,400);assert.equal((await request('leads',{method:'POST',body:{kind:'contact',name:'Bot',email:a.user.email,message:'bad',language:'en',consent:'on',website:'spam'}})).status,400)});
await t.test('logout revokes session',async()=>{assert.equal((await request('auth/logout',{method:'POST',cookie:a.cookie})).status,200);assert.equal((await request('workspace',{cookie:a.cookie})).status,401)});
}finally{if(admin)await request('auth/logout',{method:'POST',cookie:admin});if(b)await request('auth/logout',{method:'POST',cookie:b.cookie});const db=JSON.parse(await fs.readFile('.data/store.json','utf8'));db.users=db.users.filter(u=>!tracked.users.includes(u.id));db.sessions=db.sessions.filter(s=>!tracked.users.includes(s.user_id));db.properties=db.properties.filter(p=>!tracked.properties.includes(p.id));db.documents=db.documents.filter(d=>!tracked.documents.includes(d.id));db.leads=db.leads.filter(l=>!tracked.leads.includes(l.id));await fs.writeFile('.data/store.json',JSON.stringify(db,null,2));for(const id of tracked.documents)await fs.unlink('.data/documents/'+id).catch(()=>{});assert.equal(db.users.length,before.users.length)}});
