'use client';
import {useEffect,useState} from 'react';
import {Eye,EyeOff,Upload,Download,ChevronDown,CheckCircle2} from 'lucide-react';
import {uploadDocument} from '@/lib/upload-client';
import type {Lang} from './site';
import type {SharedResource} from '@/lib/shared-resources';
export default function AdminTools({lang}:{lang:Lang}){
 const t=(en:string,zh:string)=>lang==='zh'?zh:en;const i=lang==='zh'?1:0;
 const[resources,setResources]=useState<SharedResource[]>([]);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const[uploadMsg,setUploadMsg]=useState('');const[uploadOK,setUploadOK]=useState(false);const[show,setShow]=useState(false);
 async function load(){try{const r=await fetch('/api/member-resources');if(!r.ok)throw Error();setResources(await r.json())}catch{setMsg(t('Unable to load resources. Refresh to try again.','资料加载失败，请刷新重试。'))}}
 useEffect(()=>{load()},[]);
 async function upload(e:React.SubmitEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);setUploadMsg('');setUploadOK(false);try{const r=await uploadDocument('member-resources',new FormData(form));if(!r.ok)throw Error();form.reset();await load();setUploadOK(true);setUploadMsg(t('Published. All signed-in members can now download this resource on the co-living page.','发布成功，所有已登录会员均可在中租共居页面下载此资料。'))}catch{setUploadMsg(t('Upload failed. Check the title, file type, and 10 MB limit.','上传失败，请检查标题、文件格式及 10 MB 大小限制。'))}finally{setBusy(false)}}
 async function password(e:React.SubmitEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));if(data.password!==data.confirmPassword){setMsg(t('New passwords must match.','两次新密码必须一致。'));return}setBusy(true);setMsg('');try{const r=await fetch('/api/auth/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw Error();form.reset();setMsg(t('Password updated. Use your new password next time. Other sessions have been signed out.','密码已修改，下次请使用新密码登录。其他登录会话已退出。'))}catch{setMsg(t('Unable to update. Check your current password and use at least 8 characters for the new password.','修改失败，请核对当前密码，新密码至少需要 8 个字符。'))}finally{setBusy(false)}}
 return <section className="admin-section admin-tools"><h2>{t('Member resource library','会员专享资料管理')}</h2><div className="resource-management"><form className="form-card" onSubmit={upload} id="shared-resource-upload"><h3>{t('Publish a member resource','发布会员专享资料')}</h3><p>{t('Visible to all signed-in members. For private owner documents, use the separate owner upload form below.','所有已登录会员可见。业主私人文件请使用下方的专属文件上传表单。')}</p><div className="form-grid" style={{marginTop:20}}><label className="field">{t('Title / Chinese title','资料标题（中文）')}<input name="title" required maxLength={200}/></label><label className="field">{t('English title (optional)','英文标题（选填）')}<input name="title_en" maxLength={200}/></label><label className="field">{t('Description / Chinese','中文说明（选填）')}<textarea name="description" maxLength={2000}/></label><label className="field">{t('English description (optional)','英文说明（选填）')}<textarea name="description_en" maxLength={2000}/></label><label className="field wide">{t('File (maximum 10 MB)','文件（最大 10 MB）')}<input name="file" type="file" required accept=".pdf,.docx,.xlsx,.csv,.txt,.png,.jpg,.jpeg"/></label></div><button className="button" disabled={busy}><Upload size={17}/>{busy?t('Uploading…','正在上传…'):t('Publish to all members','发布给所有会员')}</button>{uploadMsg&&<div className={'message upload-feedback'+(uploadOK?' success':' error')} role="status">{uploadOK&&<CheckCircle2 size={20}/>}<span>{uploadMsg}</span></div>}</form><div className="published-resources"><h3>{t('Published member resources','已发布的会员资料')}</h3>{resources.map(r=><div className="document-row" key={r.id}><div><div><strong>{r.title[i]}</strong><small>{t('All members','全体会员')} · {r.filename}</small></div></div><a className="text-link" href={'/api/member-resources/'+r.id}><Download size={16}/>{t('Download','下载')}</a></div>)}</div></div><details className="password-settings"><summary>{t('Account settings · Change password','账户设置 · 修改密码')}<ChevronDown size={18}/></summary><form className="form-card" onSubmit={password} id="admin-password"><h3>{t('Change password','修改密码')}</h3><p>agentkelly2024@gmail.com</p><div className="form-grid" style={{marginTop:20}}>{[['currentPassword','Current password','当前密码'],['password','New password (8+ characters)','新密码（至少 8 个字符）'],['confirmPassword','Confirm new password','再次输入新密码']].map(([name,en,zh])=><label className="field wide" key={name}>{t(en,zh)}<input name={name} type={show?'text':'password'} autoComplete={name==='currentPassword'?'current-password':'new-password'} minLength={name==='currentPassword'?1:8} maxLength={128} required/></label>)}</div><button type="button" className="password-visibility" onClick={()=>setShow(!show)} aria-pressed={show}>{show?<EyeOff size={18}/>:<Eye size={18}/>} {show?t('Hide passwords','隐藏密码'):t('Show passwords','显示密码')}</button><button className="button" disabled={busy}>{t('Save new password','保存新密码')}</button>{msg&&<div className="message" role="status">{msg}</div>}</form></details></section>
}
