'use client';
import type {ReactNode} from 'react';
import {ArrowRight,ArrowUpRight,ChevronDown,Check} from 'lucide-react';
import MemberLink from './member-link';
import type {Lang} from './site';
export default function HomeStory({lang,comparison}:{lang:Lang;comparison:ReactNode}){
const t=(en:string,zh:string)=>lang==='zh'?zh:en;const href=(p:string)=>p+(lang==='zh'?'?lang=zh':'');
const actions=()=> <div className="story-actions"><MemberLink className="button" href={href('/co-living')}>{t('Learn more','了解更多')}<ArrowRight size={17}/></MemberLink><MemberLink className="button secondary" href={href('/co-living/evaluate')}>{t('Evaluate your property','评估我的房产')}<ArrowUpRight size={17}/></MemberLink></div>;
const label=(letter:string,word:string,zh:string)=><div className="story-label"><span>{letter}</span><strong>{word}</strong>{lang==='zh'&&<span className="story-section-title">{zh}</span>}</div>;
return <div className="home-story"><nav className="container story-index" aria-label={t('Explore co-living','共居导览')}>{[['what','What'],['why','Why'],['how','How'],['who','Who'],['questions','Q&A']].map(([id,title])=><a href={'#'+id} key={id}>{title}</a>)}</nav>
<section id="what" className="container story-section story-what"> <div>{label('A','What','什么是中租共居')}<h1>{t('Private rooms. Shared spaces. A better use of your home.','独立卧室，共享空间\n让一套房产发挥更多价值')}</h1><p className="story-lead">{t('Co-living is a residential rental model: residents rent their own furnished bedrooms and share a kitchen, living room, and, where applicable, bathrooms. Instead of one household renting the whole home, several residents each pay for their own room.','中租共居是一种居住型出租模式：住户分别租用家具齐备的独立卧室，共享厨房、客厅及适用的公共卫浴。与一个家庭租下整套房屋不同，多位住户各自租住一个房间，分别支付租金。')}</p><ul className="story-points">{[['For residents: a private room without the cost of renting an entire home.','住户：拥有独立卧室，无需承担整套房屋的租金。'],['For owners: room-based income with coordinated day-to-day management.','业主：按房间获取租金，由专业团队协调日常管理。'],['For the home: clear house rules and shared-space routines.','房屋：以明确的居住规则和公共空间管理维持秩序。']].map(([en,zh])=><li key={en}><Check size={18}/>{t(en,zh)}</li>)}</ul>{actions()}</div><figure><img src="/images/family-living.webp" alt={t('Furnished shared living room and kitchen','家具齐备的共享客厅与厨房')} fetchPriority="high"/><figcaption>{t('A place to live, with room for privacy and connection.','独立生活，也有共享空间')}</figcaption></figure></section>
<section id="why" className="story-section story-why"><div className="container">{label('B','Why','为什么选择中租共居')}<h2>{t('Make cash flow part of the plan','让现金流成为持有房产的底气')}</h2><p className="story-lead">{t('Property appreciation is uncertain, while financing, insurance, taxes, and maintenance still need to be paid. When appreciation slows or holding costs rise, the income left after expenses becomes especially important. Co-living offers another way to use existing space—but the full operating budget must work.','房价上涨存在不确定性，贷款、保险、税费和维护支出却需要持续承担。当升值放缓或持有成本上升时，扣除费用后能留下多少现金流，就更值得关注。中租共居为现有空间提供另一种出租思路，关键仍是把完整收支算清楚。')}</p></div>{comparison}<div className="container">{actions()}</div></section>
<section id="how" className="container story-section">{label('C','How','如何落地运营')}<h2>{t('Five steps, from an address to daily operations','五个步骤，从房产地址到日常运营')}</h2><p className="story-lead">{t('Savannah Rental takes care of every step for you.','Savannah Rental 替您做好每一步')}</p><ol className="story-steps">{[
['Analyze','分析','Is this property suitable?','这套房产适合吗？','Review the address, layout, existing use, local rental demand, and applicable rules. Compare the current rental baseline with room-based income and costs.','查看地址、户型、使用现状、当地租住需求与适用规定，对比现有出租基准与按房间出租的收入和成本。'],
['Plan','规划','What would the numbers and scope look like?','收支和管理范围如何安排？','Estimate setup costs, utilities, vacancy, maintenance, and management expenses. Agree on a workable rental strategy, budget, responsibilities, and timeline.','测算配置投入、水电、空置、维修与管理费用，明确出租策略、预算、双方职责和推进时间。'],
['Prepare','准备','What needs to be ready before move-in?','入住前需要准备什么？','Coordinate furnishings, locks, household supplies, and shared-space setup. Prepare house rules and a practical checklist for the home.','协调家具、门锁、日常用品及公共空间配置，制定居住规则，并按清单检查房屋准备情况。'],
['Launch','上线','How will the rooms reach suitable residents?','如何让合适的住户找到房源？','Prepare photos, room descriptions, pricing, and listings. Coordinate inquiries, the agreed resident-screening process, and move-in arrangements.','准备照片、房间介绍、定价和房源发布，协调咨询、约定的住户审核流程及入住安排。'],
['Operate','运营','How will the home keep running well?','如何持续做好管理？','Coordinate resident communication, shared-space cleaning, maintenance, and owner updates. Review occupancy and pricing as conditions change.','协调住户沟通、公共空间清洁、维修与业主反馈，并结合实际情况复盘入住率和定价。']
].map(([en,zh,qen,qzh,den,dzh],i)=><li key={en}><details className="story-step"><summary><span className="story-step-number">0{i+1}</span><h3>{en}{lang==='zh'?' · '+zh:''}</h3><ChevronDown size={20}/></summary><div className="story-step-content"><h4>{t(qen,qzh)}</h4><p>{t(den,dzh)}</p></div></details></li>)}</ol>{actions()}</section>
<section id="who" className="story-section story-who"><div className="container">{label('D','Who · SavannahRental','为什么选择 SavannahRental')}<h2>{t('Analysis backed by hands-on operating experience','懂分析，也懂实际运营')}</h2><p className="story-lead">{t('SavannahRental brings an owner’s perspective to rental strategy and the practical work that follows. We help you understand the options, prepare the home, and coordinate ongoing management.','SavannahRental 站在业主的角度制定出租策略，也亲力亲为做好落地工作。从理解不同出租选择，到房屋筹备与持续管理，让分析与执行衔接起来。')}</p><div className="story-strengths">{[
['Gold Host experience','Gold Host 运营经验','Achieved Gold Host status within approximately six months of co-living operations.','开展共居运营后，约六个月获得 Gold Host 状态。'],
['The whole financial picture','关注完整收支','We consider rental potential alongside setup, vacancy, and operating costs—not gross rent alone.','综合考虑出租潜力、配置投入、空置与运营成本，帮助业主理解收入背后的支出。'],
['Practical management systems','实际管理流程','Experience with property setup, pricing, resident communication, cleaning, and maintenance.','将房屋准备、定价、住户沟通、清洁和维修落实到日常流程。'],
['Clear communication in two languages','中英文沟通支持','English and Chinese support helps owners understand the strategy, next steps, and shared property documents.','提供中英文沟通，帮助业主理解出租策略、下一步安排与房产文件。']
].map(([en,zh,den,dzh])=><article key={en}><h3>{t(en,zh)}</h3><p>{t(den,dzh)}</p></article>)}</div>{actions()}</div></section>
<section id="questions" className="container story-section">{label('E','Q&A','常见问题')}<h2>{t('Questions owners ask before getting started','开始之前，业主最关心的问题')}</h2><details className="story-faq-disclosure"><summary><span>{t('Explore the questions owners ask','展开查看业主常见问题')}</span><ChevronDown size={22}/></summary><div className="story-faq">{[
['Does every property work for co-living?','每套房产都适合中租共居吗？','No. Layout, location, demand, applicable rules, and costs all matter. The first step is to assess your specific property.','并非如此。户型、地段、需求、适用规定和成本都很重要，需要先评估您的具体房产。'],
['Will co-living earn more than a whole-home lease?','中租共居一定比整套长租赚得更多吗？','Room-based rental can increase gross income, but profit depends on occupancy, setup costs, and ongoing expenses. We compare the complete budget before recommending a strategy.','按房间出租有机会提高总租金，但利润取决于入住率、配置投入与持续支出。我们会先对比完整预算，再探讨适合的策略。'],
['What happens when a room is vacant?','如果有房间空置，会怎样？','Other occupied rooms can continue producing rent. This spreads vacancy exposure across rooms, although several rooms can still be vacant at the same time.','其他已出租房间仍可贡献租金，让空置风险分散到不同房间；但也可能出现多个房间同时空置的情况。'],
['Do I need to furnish the property?','需要为房屋配置家具吗？','Our model generally uses furnished bedrooms and equipped shared spaces. What needs purchasing depends on the home’s existing condition and agreed setup plan. Members can download the preparation checklist.','我们的模式通常采用家具齐备的卧室与配置完善的公共空间。具体采购内容取决于房屋现状和约定的筹备方案，会员可下载相关准备清单。'],
['Who manages residents and maintenance?','住户沟通和维修由谁负责？','SavannahRental coordinates the services agreed in the management scope, including resident communication, cleaning, and maintenance. Responsibilities are clarified before launch.','SavannahRental 按约定的管理范围协调住户沟通、清洁和维修等服务，并在上线前明确双方职责。'],
['Can I see real examples before deciding?','决定之前，可以看看真实案例吗？','Yes. Sign in or register to view the detailed Pooler and Atlanta figures and access the shared member document library.','可以。登录或注册后，即可查看 Pooler 与 Atlanta 的详细数字对比，并获取会员共享资料。'],
['How do I get an evaluation?','如何申请房产评估？','Choose Evaluate your property, sign in or register, then provide your address, property details, and rental goals. Our team reviews the information and discusses next steps.','点击“评估我的房产”，登录或注册后填写地址、房产信息与出租目标。团队会查看资料，与您讨论下一步安排。']
].map(([en,zh,den,dzh])=><details key={en}><summary>{t(en,zh)}<ChevronDown size={18}/></summary><p>{t(den,dzh)}</p></details>)}</div></details>{actions()}</section></div>
}
