'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {ArrowUpRight,ArrowRight,House,ChartNoAxesCombined,KeyRound,ShieldCheck,Menu,X,Globe,Check,Mail,MapPin,Layers,Users,ClipboardCheck,ChevronDown,Building2,FileText,LogOut,Upload} from 'lucide-react';
import HomeStory from './home-story';
import Workspace from './workspace';
import LeadForm from './lead-form';
import AuthForm from './auth-form';
import CaseStudy from './case-studies';
import MemberResources from './member-resources';
import MemberLink,{MembershipContext} from './member-link';
export type Lang='en'|'zh';
export const tr=(lang:Lang,en:string,zh:string)=>lang==='en'?en:zh;
const footerNav=[['/','Home','首页'],['/long-term','Long-Term Rental','长租管理'],['/co-living','Co-Living','中租·共居'],['/co-living/case-study','Case Studies','运营案例'],['/co-living/how-it-works','How It Works','运营流程'],['/about','About','关于我们'],['/contact','Contact','联系我们']];
const nav=footerNav.slice(0,3).map(([url,en,zh])=>[url,en,url==='/long-term'?'长租':url==='/co-living'?'中租共居':zh]);
export default function Site({path,initialLang,signedIn=false}:{path:string,initialLang?:Lang,signedIn?:boolean}){
const[signingOut,setSigningOut]=useState(false);const[logoutError,setLogoutError]=useState(false);
async function signout(){setSigningOut(true);setLogoutError(false);try{const r=await fetch('/api/auth/logout',{method:'POST'});if(!r.ok)throw Error();location.href='/'+(lang==='zh'?'?lang=zh':'')}catch{setLogoutError(true);setSigningOut(false)}}
const [lang,setLang]=useState<Lang>(initialLang||'en');
useEffect(()=>{const p=new URLSearchParams(location.search).get('lang');const saved=p||localStorage.getItem('sr-language');if(saved==='zh'||saved==='en'){setLang(saved);localStorage.setItem('sr-language',saved)}},[initialLang,path]);
useEffect(()=>{document.documentElement.lang=lang==='en'?'en':'zh-Hans';},[lang]);
const t=(a:string,b:string)=>tr(lang,a,b);const href=(p:string)=>p+(lang==='zh'?'?lang=zh':'');
function language(){const v=lang==='en'?'zh':'en';setLang(v);localStorage.setItem('sr-language',v);const url=new URL(location.href);url.searchParams.set('lang',v);history.replaceState(null,'',url)}
const cta=<MemberLink className="button" href={href('/co-living/evaluate')}>{t('Evaluate My Property','评估我的房产')}<ArrowUpRight size={17}/></MemberLink>;
const discoveryFirst=path==='/'||path==='/co-living';
const discoveryCTA=<Link className="button" href={path==='/'?'#what':href('/')+'#what'}>{path==='/co-living'?t('Understand Co-Living','了解共居模式'):t('Explore Co-Living','了解中租·共居')}<ArrowRight size={17}/></Link>;
const headerCTA=discoveryFirst?discoveryCTA:cta;
return <MembershipContext.Provider value={signedIn}><a className="skip" href="#main">{t('Skip to content','跳至正文')}</a><header className="header"><div className="container header-inner"><Link className="brand" href={href('/')} aria-label="SavannahRental home"><span className="brand-icon"><House size={24}/></span><span>Savannah<span className="brand-light">Rental</span><small>{t('PROPERTY MANAGEMENT','专业物业管理')}</small></span></Link><div className="header-actions"><button className="language" onClick={language} aria-label={t('Switch to Chinese','Switch to English')}><Globe size={15}/>{t('中文','EN')}</button>{signedIn?<><Link className="owner-link" href={href('/portal')}><KeyRound size={14}/>{t('My account','会员中心')}</Link><button className="logout-button" onClick={signout} disabled={signingOut}><LogOut size={15}/>{signingOut?t('Signing out…','正在登出…'):t('Log out','登出')}</button></>:<Link className="owner-link" href={href('/login')}><KeyRound size={14}/>{t('Member login','会员登录')}</Link>}<div className="header-cta">{headerCTA}</div></div></div><nav className="container visible-nav" aria-label={t('Main navigation','主导航')}>{nav.map(([url,en,zh])=><Link key={url} className={path===url?'active':''} aria-current={path===url?'page':undefined} href={href(url)}>{t(en,zh)}</Link>)}</nav></header><main id="main">{logoutError&&<div className="container message error" role="alert">{t('Unable to log out. Please try again.','登出失败，请重试。')}</div>}
{path==='/'&&<HomeStory lang={lang} comparison={<Comparison lang={lang}/>}/>}
{path==='/co-living'&&<><PageHeading lang={lang} eyebrow={t('CO-LIVING · MEMBER RESOURCES','中租共居 · 会员资料')} title={t('Explore the numbers. Prepare your property.','查看真实数字，准备您的房产')} text={t('Detailed rental comparisons and practical documents to support your next step.','通过详细租金对比与实用资料，为下一步房产决策做准备。')}/><div className="container member-overview-link"><Link className="text-link" href={href('/')+'#what'}>{t('What · Why · How · Who · Q&A — start with the public guide','What · Why · How · Who · Q&A — 查看首页完整介绍')}<ArrowRight size={17}/></Link></div>{signedIn?<><CaseStudy lang={lang} full/><MemberResources lang={lang}/></>:<section className="container section"><div className="note-panel"><h2>{t('More detail, included with membership','登录会员，继续深入了解')}</h2><p>{t('Explore the Pooler and Atlanta monthly rental comparisons, the 5252 projection workbook, and the landlord preparation checklist.','查看 Pooler 与 Atlanta 月度租金对比、5252 收支测算工作簿与房东装修采购清单。')}</p><div className="story-actions"><MemberLink className="button" href={href('/co-living')}>{t('Learn more','了解更多')}<ArrowRight size={17}/></MemberLink>{cta}</div></div></section>}<CTA lang={lang}/></>}
{path==='/long-term'&&<><Hero lang={lang} eyebrow={t('LONG-TERM RENTAL','长租管理')} title={t('Stable leasing. Professional operations.','稳定出租，专业运营')} text={t('Straightforward whole-property management, with the day-to-day details taken care of.','整套房屋出租管理，为您协调日常事务，让持有房产更省心。')} image="shared-living"/><section className="section container"><div className="eyebrow">{t('LONG-TERM RENTAL MANAGEMENT','全流程长租管理')}</div><h2>{t('From the first listing to the next renewal.','从首次招租，到下一次续约')}</h2><Cards lang={lang} items={[[ 'Property marketing','房源推广','Position the property and coordinate listings to reach prospective residents.','明确房源定位，协调发布租赁信息，接触潜在租客。'],['Tenant placement & leasing','租客招募与租约协调','Coordinate tenant placement and the leasing process.','协调租客招募与签约流程。'],['Resident communication','住户沟通','Provide a clear point of contact for everyday property questions.','为日常房屋问题提供清晰的沟通渠道。'],['Maintenance coordination','维护协调','Coordinate repairs and keep owners informed about property needs.','协调维修，并及时向业主说明房屋维护需求。'],['Owner communication','业主沟通','Keep property information and shared documents organized.','整理房产信息与共享文件，保持沟通透明。'],['Ongoing management','持续管理','Support the property through occupancy, renewals, and changing needs.','在入住、续租与需求变化过程中持续支持房产运营。']]}/></section><CTA lang={lang}/></>}
{path==='/about'&&<><Hero lang={lang} eyebrow={t('ABOUT SAVANNAHRENTAL','关于 SAVANNAHRENTAL')} title={t('Property management with an owner’s mindset.','以业主的思维，做好物业管理')} text={t('Good management begins with understanding the economics of the property—and follows through with hands-on operation.','好的管理，从理解房产的经济逻辑开始，并通过扎实的日常运营落地。')} image="family-living"/><section className="section container intro-grid"><h2>{t('Analyze. Operate. Keep improving.','分析、运营、持续改善')}</h2><div><p>{t('SavannahRental combines traditional property management with newer rental strategies designed around changing housing markets. For some owners, long-term leasing is the right answer. For others, professionally operated co-living may put the home to better use.','SavannahRental 将传统物业管理与适应市场变化的新型出租策略相结合。对部分业主而言，长租是合适的选择；对另一些业主而言，专业运营的中租·共居可能更能发挥房屋的使用价值。')}</p><p>{t('Our role is to help owners understand the options, choose a suitable strategy, and manage the practical work that follows.','我们的角色，是帮助业主理解选择、确定适合的策略，并做好后续的实际管理工作。')}</p></div></section><section className="green-section"><div className="container"><h2>{t('Our co-living experience','我们的中租·共居经验')}</h2><Experience lang={lang}/></div></section><CTA lang={lang}/></>}
{path==='/co-living/how-it-works'&&<><PageHeading lang={lang} eyebrow={t('HOW IT WORKS','运营流程')} title={t('From property analysis to ongoing operation.','从房产分析，到持续运营')} text={t('A considered process, with practical work at every stage.','每个阶段都有明确思路，也有扎实的执行。')}/><Process lang={lang}/><section className="container section"><div className="note-panel"><h3>{t('You own the property. We operate the strategy.','您持有房产，我们运营策略')}</h3><p>{t('Every property is different. Preparation, timelines, and the final rental model depend on the property, local requirements, and the agreed management scope.','每套房产情况不同。准备工作、时间安排与最终出租模式，需结合房产条件、当地要求及约定的管理范围确定。')}</p></div></section><CTA lang={lang}/></>}
{path==='/co-living/case-study'&&<><PageHeading lang={lang} eyebrow={t('PROPERTY CASE STUDY','房产案例')} title={t('Pooler & Atlanta. Real numbers, in context.','Pooler 与 Atlanta：真实数据，清晰对比')} text={t('Explore reported co-living collections and payouts alongside owner-confirmed whole-home rental baselines.','结合业主确认的整套长租基准，查看共居实收与平台打款记录。')}/><CaseStudy lang={lang} full/><CTA lang={lang}/></>}
{path==='/co-living/evaluate'&&<><PageHeading lang={lang} eyebrow={t('PROPERTY EVALUATION','房产评估')} title={t('What could your property produce?','您的房产，有多大潜力？')} text={t('Tell us about your property. We’ll review the details and discuss which rental strategy may fit.','告诉我们您的房产情况。我们会查看资料，与您探讨适合的出租策略。')}/><div className="container form-layout section"><LeadForm lang={lang} kind="evaluation"/><aside><div className="aside-card"><ClipboardCheck size={30}/><h3>{t('Start with a conversation.','从一次沟通开始')}</h3><p>{t('We consider the location, layout, current use, setup needs, and operating economics.','我们综合考虑地段、户型、现状、配置需求与运营收支。')}</p><ul className="check-list">{[['A property-specific review','针对具体房产进行分析'],['A practical rental strategy','探讨可落地的出租策略'],['Clear next steps','明确下一步安排']].map(([a,b])=><li key={a}><Check size={17}/>{t(a,b)}</li>)}</ul><small>{t('An evaluation is not a guarantee of income.','评估不构成收益保证。')}</small></div><p className="privacy-note">{t('Your property address and contact details are shared with our management team, not published on the website.','您的房产地址与联系方式仅供管理团队使用，不会公开展示。')}</p></aside></div></>}
{path==='/contact'&&<><PageHeading lang={lang} eyebrow={t('LET’S TALK','联系我们')} title={t('A better strategy starts here.','从这里，寻找更好的出租策略')} text={t('Questions about long-term management or co-living? Tell us what you have in mind.','想了解长租管理或中租·共居？欢迎告诉我们您的需求。')}/><div className="container form-layout section"><LeadForm lang={lang} kind="contact"/><aside className="aside-card"><Mail/><h3>{t('Talk with SavannahRental','联系 SavannahRental')}</h3><a className="email-link" href="mailto:agentkelly2024@gmail.com">agentkelly2024@gmail.com</a><hr/><MapPin/><p>{t('Savannah, Georgia & surrounding areas','美国乔治亚州萨凡纳及周边地区')}</p><p>{t('English & Chinese support','提供中文与英文沟通')}</p></aside></div></>}
{(path==='/login'||path==='/register')&&<AuthForm lang={lang} register={path==='/register'}/>}
{(path.startsWith('/portal')||path==='/admin')&&<Workspace lang={lang} path={path}/>}
</main><footer><div className="container footer-grid"><div><Link className="brand" href={href('/')}><span className="brand-icon"><House size={23}/></span><span>Savannah<span className="brand-light">Rental</span></span></Link><p>{t('Smarter rental strategy. Professional operation.','更明智的出租策略，更专业的运营。')}<br/>{t('Better property performance.','让房产表现更出色。')}</p></div><div><strong>{t('Explore','了解更多')}</strong>{footerNav.map(([url,en,zh])=><Link key={url} href={href(url)}>{t(en,zh)}</Link>)}</div><div><strong>{t('For property owners','业主服务')}</strong><Link href={href('/co-living/evaluate')}>{t('Property evaluation','房产评估')}</Link><Link href={href('/login')}>{t('Owner portal','业主中心')}</Link><Link href={href('/register')}>{t('Create an account','注册账户')}</Link></div><div><strong>{t('Let’s connect','联系团队')}</strong><a href="mailto:agentkelly2024@gmail.com">agentkelly2024@gmail.com</a><span>{t('Savannah, Georgia','乔治亚州 · 萨凡纳')}</span><span>{t('English / 中文','中文 / English')}</span></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} SavannahRental. {t('All rights reserved.','保留所有权利。')}</span><span>{t('Property performance varies. No income is guaranteed.','房产表现因具体情况而异，不保证收益。')}</span></div></footer></MembershipContext.Provider>}
function PageHeading({lang,eyebrow,title,text}:{lang:Lang,eyebrow:string,title:string,text:string}){return <section className="page-heading"><div className="container"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{text}</p></div></section>}
function Hero({lang,eyebrow,title,text,image,discovery=false}:{lang:Lang,eyebrow:string,title:string,text:string,image:string,discovery?:boolean}){return <section className="container sub-hero"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p className="lead">{text}</p><MemberLink className="button" href={discovery?'#co-living-concept':'/co-living/evaluate'+(lang==='zh'?'?lang=zh':'')}>{discovery?tr(lang,'Discover how Co-Living works','先了解共居模式'):tr(lang,'Evaluate My Property','评估我的房产')}{discovery?<ArrowRight size={17}/>:<ArrowUpRight size={17}/>}</MemberLink></div><img src={'/images/'+image+'.webp'} alt={image==='private-bedroom'?tr(lang,'Furnished private bedroom with natural light','采光明亮、家具齐备的独立卧室'):tr(lang,'Furnished living room and shared spaces','家具齐备的客厅与共享空间')}/></section>}
function Cards({lang,items}:{lang:Lang,items:string[][]}){return <div className="info-grid">{items.map(([en,zh,ent,zht],i)=><article className="info-card" key={en}><span className="step-number">0{i+1}</span><h3>{tr(lang,en,zh)}</h3><p>{tr(lang,ent,zht)}</p></article>)}</div>}
function Experience({lang}:{lang:Lang}){return <><Cards lang={lang} items={[[ 'Gold Host experience','Gold Host 运营经验','Achieved Gold Host status within approximately six months of co-living operations.','开展中租·共居运营后，约六个月获得 Gold Host 状态。'],['Practical operating systems','实际运营体系','Experience with setup, resident communication, pricing, cleaning, and maintenance.','涵盖房屋准备、住户沟通、定价、清洁与维护的实际经验。'],['Owner & industry education','业主教育与行业交流','Structured co-living courses and educational seminars involving PadSplit executives.','开发中租·共居课程，并参与涉及 PadSplit 高管的教育研讨与交流。']]}/><p className="fine-print">{tr(lang,'References to PadSplit describe educational participation and operating experience, not an official partnership or endorsement.','提及 PadSplit 仅用于说明教育交流和运营经历，不代表官方合作或背书。')}</p></>}
function Process({lang,compact=false}:{lang:Lang,compact?:boolean}){const t=(a:string,b:string)=>tr(lang,a,b);return <section className="section container"><div className="section-heading"><div><div className="eyebrow">{t('A CLEAR PATH FORWARD','清晰的推进路径')}</div><h2>{t('From possibility to a working property.','从房产潜力，到实际运营')}</h2></div>{compact&&<MemberLink className="text-link" href={'/co-living/how-it-works'+(lang==='zh'?'?lang=zh':'')}>{t('Our process','查看流程')}<ArrowRight size={17}/></MemberLink>}</div><div className="process-grid">{[['Analyze','分析','Evaluate the location, layout, and economics.','评估地段、户型与收支情况。'],['Plan','规划','Decide what makes financial and operational sense.','判断财务与运营上的可行性。'],['Prepare','准备','Coordinate furniture, locks, supplies, and setup.','协调家具、门锁、用品与房屋配置。'],['Launch','上线','Prepare listings and launch through suitable channels.','准备房源资料，通过合适渠道推出。'],['Operate','运营','Coordinate residents, cleaning, maintenance, and management.','协调住户沟通、清洁、维护与管理。']].map(([en,zh,ent,zht],i)=><article key={en}><div className="process-number">0{i+1}</div><h3>{t(en,zh)}</h3><p>{t(ent,zht)}</p></article>)}</div></section>}
function Comparison({lang}:{lang:Lang}){const t=(a:string,b:string)=>tr(lang,a,b);return <section className="comparison-section"><div className="container"><div className="eyebrow">{t('UNDERSTAND YOUR OPTIONS','了解不同选择')}</div><h2>{t('Three rental models. Three different strategies.','三种出租模式，三种不同策略')}</h2><div className="table-scroll" tabIndex={0} role="region" aria-label={t('Rental model comparison','出租模式比较')}><table><thead><tr>{[['',''],['Long-Term Rental','长租'],['Co-Living','中租·共居'],['Airbnb / Short-Term','Airbnb / 短租']].map(([a,b],i)=><th key={i} scope="col">{t(a,b)}</th>)}</tr></thead><tbody>{[[['Rental structure','出租结构'],['Entire property','整套房屋'],['Private bedrooms','独立卧室'],['Entire property or room','整套或单间']],[['Typical resident','典型住户'],['One household','一个家庭'],['Individual residents','独立住户'],['Travelers','旅行者']],[['Stay length','居住周期'],['Longer term','长期'],['Medium / longer residential stays','中长期居住'],['Days / weeks','数天或数周']],[['Furnished','家具配置'],['Usually no','通常不配'],['Usually yes','通常配备'],['Yes','配备']],[['Income sources','收入来源'],['One lease','单份租约'],['Multiple rooms','多个房间'],['Frequent bookings','频繁预订']],[['Turnover','周转频率'],['Low','低'],['Moderate','中等'],['High','高']],[['Operating intensity','运营强度'],['Lower','较低'],['Moderate / high','中等至较高'],['High','高']],[['Income stability','收入稳定性'],['Generally stable','通常较稳定'],['Spread among rooms','分散于多个房间'],['Can fluctuate','可能波动']],[['Local restrictions','当地规定'],['Rental rules apply','适用租赁规定'],['Depends on local rules','取决于当地规定'],['Often more regulated','通常有更多监管要求']]].map((row,i)=><tr key={i}>{row.map(([a,b],j)=>j===0?<th scope="row" key={j}>{t(a,b)}</th>:<td key={j}>{t(a,b)}</td>)}</tr>)}</tbody></table></div><div className="comparison-note"><ShieldCheck/><div><h3>{t('Why choose Co-Living?','中租·共居的三大优势')}</h3><div className="benefit-grid">{[['More earning potential than a whole-home lease','比整套长租，更多收益潜力','Renting bedrooms separately can increase total rental income and create room for higher profit after operating costs.','按房间分别出租，有机会提高总租金收入，在合理控制运营成本后，争取更高利润。'],['Spread vacancy risk across rooms','分散空置风险，现金流更稳健','With a whole-home lease, vacancy can pause all rent. With co-living, occupied rooms can keep generating income while another room is being filled.','整套长租一旦空置，租金收入可能全部中断。共居按房间出租，个别房间空置时，其他已出租房间仍可持续贡献租金。'],['Less turnover than nightly Airbnb stays','比 Airbnb 短租，减少周转成本','Longer residential stays can mean fewer check-ins, turnover cleanings, and linen changes, reducing these operating costs compared with frequent short stays.','较长的居住周期，可减少频繁入住退房、换客清洁与床品更换，从而降低这部分日常运营成本。']].map(([en,zh,bodyEn,bodyZh])=><article key={en}><h4>{t(en,zh)}</h4><p>{t(bodyEn,bodyZh)}</p></article>)}</div></div></div></div></section>}
function FAQ({lang}:{lang:Lang}){const t=(a:string,b:string)=>tr(lang,a,b);return <section className="section container faq"><div><div className="eyebrow">{t('A FEW COMMON QUESTIONS','常见问题')}</div><h2>{t('Before you get started.','开始之前，先了解这些')}</h2></div><div>{[['Will every house work for co-living?','每套房屋都适合中租·共居吗？','No. Layout, location, local rules, demand, and operating costs all matter. We start with a property-specific evaluation.','并非如此。户型、地段、当地规定、需求与运营费用都很重要。我们会先评估具体房产。'],['Is higher income guaranteed?','是否保证更高收益？','No. Co-living may improve utilization, but net results depend on occupancy, pricing, setup costs, and ongoing expenses.','不保证。中租·共居可能提高空间利用率，但净收益取决于入住率、定价、配置投入与日常费用。'],['Who handles day-to-day operations?','谁负责日常运营？','SavannahRental coordinates the agreed scope of resident communication, cleaning, maintenance, and ongoing management.','SavannahRental 按约定范围协调住户沟通、清洁、维修与持续管理。']].map(([a,b,c,d])=><details key={a}><summary>{t(a,b)}<ChevronDown size={18}/></summary><p>{t(c,d)}</p></details>)}</div></section>}
function CTA({lang}:{lang:Lang}){return <section className="container cta-section"><div><div className="eyebrow">{tr(lang,'LET’S LOOK AT THE POSSIBILITIES','一起看看，房产还有哪些可能')}</div><h2>{tr(lang,'Could your property work harder?','您的房产，能否更进一步？')}</h2><p>{tr(lang,'Start with your property. Build a strategy around it.','从了解房产开始，制定适合的出租策略。')}</p></div><MemberLink className="button" href={'/co-living/evaluate'+(lang==='zh'?'?lang=zh':'')}>{tr(lang,'Evaluate My Property','评估我的房产')}<ArrowUpRight size={17}/></MemberLink></section>}



