import 'server-only';
import {siteUrl} from './site-url';
import {initialResources,type SharedResource} from './shared-resources';
import {promises as fs} from 'node:fs';
import path from 'node:path';
import {randomUUID,randomBytes,scryptSync,timingSafeEqual,createHash} from 'node:crypto';
import {createClient} from '@supabase/supabase-js';
export const ADMIN_EMAIL='agentkelly2024@gmail.com';
export const local=process.env.DATA_BACKEND==='local'||(!process.env.DATA_BACKEND&&process.env.NODE_ENV!=='production');
export type User={id:string;email:string;name:string;role:'owner'|'admin';password?:string};
export type Property={id:string;owner_id:string;title:string;address:string;strategy:string;status:string;bedrooms:number|null;contract_status?:'unsigned'|'signed';notes:string;created_at:string};
export type Document={id:string;owner_id:string;property_id:string|null;title:string;filename:string;storage_path:string;mime:string;size:number;created_at:string};
export type Lead={id:string;kind:string;language:string;email:string;notification:string;created_at:string;[key:string]:unknown};
type DB={sharedResources?:SharedResource[];users:User[];sessions:{token:string;user_id:string;expires:number}[];properties:Property[];documents:Document[];leads:Lead[]};
const root=path.join(process.cwd(),'.data');
let queue:Promise<unknown>=Promise.resolve();
export async function transaction<T>(fn:(db:DB)=>T|Promise<T>):Promise<T>{if(process.env.NODE_ENV==='production'&&process.env.ALLOW_LOCAL_PREVIEW!=='true')throw new Error('Local storage disabled in production');const op=queue.then(async()=>{await fs.mkdir(root,{recursive:true});let db:DB;try{db=JSON.parse(await fs.readFile(path.join(root,'store.json'),'utf8'))}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;db={users:[],sessions:[],properties:[],documents:[],leads:[]}}const result=await fn(db);const temp=path.join(root,'store-'+randomUUID()+'.tmp');await fs.writeFile(temp,JSON.stringify(db,null,2),{mode:0o600});await fs.rename(temp,path.join(root,'store.json'));return result});queue=op.catch(()=>{});return op}
export function scoped(token?:string){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key)throw Error('Supabase public configuration missing');return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false},...(token?{global:{headers:{Authorization:'Bearer '+token}}}:{})})}
export function cloud(){if(!process.env.NEXT_PUBLIC_SUPABASE_URL||!process.env.SUPABASE_SERVICE_ROLE_KEY)throw new Error('Supabase is not configured');return createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}})}
export function hashPassword(password:string){const salt=randomBytes(16).toString('hex');return salt+':'+scryptSync(password,salt,64).toString('hex')}
export function verifyPassword(password:string,stored:string){const[salt,hash]=stored.split(':');const actual=scryptSync(password,salt,64);const expected=Buffer.from(hash,'hex');return expected.length===actual.length&&timingSafeEqual(actual,expected)}
export const hashToken=(token:string)=>createHash('sha256').update(token).digest('hex');
export async function getUser(token:string|undefined):Promise<User|null>{if(!token)return null;if(local)return transaction(db=>{const s=db.sessions.find(s=>s.token===hashToken(token)&&s.expires>Date.now());if(!s)return null;const u=db.users.find(u=>u.id===s.user_id);return u?{id:u.id,name:u.name,email:u.email,role:u.role}:null});const c=scoped(token);const {data,error}=await c.auth.getUser(token);if(error||!data.user)return null;const {data:profile}=await c.from('profiles').select('id,name,email,role').eq('id',data.user.id).single();return profile as User|null}
export async function authenticate(email:string,password:string,name?:string){if(local)return transaction(db=>{let user=db.users.find(u=>u.email===email);if(name!==undefined){if(user||email===ADMIN_EMAIL)throw new Error('Registration unavailable');user={id:randomUUID(),email,name,role:'owner',password:hashPassword(password)};db.users.push(user)}else if(!user||!verifyPassword(password,user.password||''))throw new Error('Invalid credentials');const token=randomBytes(32).toString('hex');db.sessions=db.sessions.filter(s=>s.expires>Date.now());db.sessions.push({token:hashToken(token),user_id:user!.id,expires:Date.now()+1000*60*60*8});return {token,user:{id:user!.id,name:user!.name,email:user!.email,role:user!.role}}});const c=scoped();const {data,error}=name!==undefined?await c.auth.signUp({email,password,options:{data:{name},emailRedirectTo:siteUrl()+'/login'}}):await c.auth.signInWithPassword({email,password});if(error)throw error;if(!data.session)return {confirm:true};const user=await getUser(data.session.access_token);return {token:data.session.access_token,user,expiresIn:data.session.expires_in}}
export async function logout(token:string){if(local)await transaction(db=>{db.sessions=db.sessions.filter(s=>s.token!==hashToken(token))});else await cloud().auth.admin.signOut(token,'local')}
export async function records(user:User,token?:string){if(local)return transaction(db=>({user,properties:db.properties.filter(p=>user.role==='admin'||p.owner_id===user.id),documents:db.documents.filter(d=>user.role==='admin'||d.owner_id===user.id),leads:user.role==='admin'?db.leads:[],owners:user.role==='admin'?db.users.map(({password,...u})=>u):[]}));const c=scoped(token);const p=c.from('properties').select('*');const d=c.from('documents').select('*');if(user.role!=='admin'){p.eq('owner_id',user.id);d.eq('owner_id',user.id)}const [pr,dr,lr,ur]=await Promise.all([p,d,user.role==='admin'?c.from('leads').select('*').order('created_at',{ascending:false}):Promise.resolve({data:[],error:null}),user.role==='admin'?c.from('profiles').select('id,name,email,role'):Promise.resolve({data:[],error:null})]);for(const r of [pr,dr,lr,ur])if(r.error)throw r.error;return {user,properties:pr.data,documents:dr.data,leads:lr.data,owners:ur.data}}
export async function addLead(data:Record<string,unknown>){const record={...data,id:randomUUID(),notification:'pending',created_at:new Date().toISOString()} as Lead;if(local)await transaction(db=>{db.leads.unshift(record)});else{const{error}=await cloud().from('leads').insert(record);if(error)throw error}let sent=false;if(process.env.RESEND_API_KEY&&process.env.NOTIFICATION_FROM){try{const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+process.env.RESEND_API_KEY,'Content-Type':'application/json','Idempotency-Key':record.id},body:JSON.stringify({from:process.env.NOTIFICATION_FROM,to:[ADMIN_EMAIL],subject:'SavannahRental: new '+record.kind+' request',text:Object.entries(record).map(([k,v])=>k+': '+String(v)).join('\n')})});sent=response.ok}catch{sent=false}}if(sent){if(local)await transaction(db=>{const lead=db.leads.find(l=>l.id===record.id);if(lead)lead.notification='sent'});else await cloud().from('leads').update({notification:'sent'}).eq('id',record.id)}return {id:record.id,notification:sent?'sent':'pending'}}
export async function addProperty(data:Omit<Property,'id'|'created_at'>,token?:string){const record={...data,id:randomUUID(),created_at:new Date().toISOString()};if(local)await transaction(db=>{if(!db.users.some(u=>u.id===data.owner_id))throw new Error('Unknown owner');db.properties.push(record)});else{const{error}=await scoped(token).from('properties').insert(record);if(error)throw error}return record}
export async function addDocument(data:Omit<Document,'id'|'created_at'|'storage_path'>,bytes:Buffer){const id=randomUUID();const record={...data,id,storage_path:data.owner_id+'/'+id,created_at:new Date().toISOString()};if(local){await transaction(db=>{if(!db.users.some(u=>u.id===data.owner_id))throw new Error('Unknown owner');if(data.property_id&&!db.properties.some(p=>p.id===data.property_id&&p.owner_id===data.owner_id))throw new Error('Property and owner do not match')});await fs.mkdir(path.join(root,'documents'),{recursive:true});await fs.writeFile(path.join(root,'documents',id),bytes,{mode:0o600});await transaction(db=>{db.documents.push(record)})}else{const c=cloud();if(data.property_id){const {data:p}=await c.from('properties').select('owner_id').eq('id',data.property_id).single();if(p?.owner_id!==data.owner_id)throw new Error('Owner mismatch')}const {error}=await c.storage.from('owner-documents').upload(record.storage_path,bytes,{contentType:data.mime});if(error)throw error;const insert=await c.from('documents').insert(record);if(insert.error){await c.storage.from('owner-documents').remove([record.storage_path]);throw insert.error}}return record}
export async function downloadDocument(user:User,id:string,token?:string){let doc:Document|undefined;if(local)doc=await transaction(db=>db.documents.find(d=>d.id===id&&(user.role==='admin'||d.owner_id===user.id)));else{const q=scoped(token).from('documents').select('*').eq('id',id);if(user.role!=='admin')q.eq('owner_id',user.id);const{data}=await q.single();doc=data as Document|undefined}if(!doc)return null;if(local)return {doc,bytes:await fs.readFile(path.join(root,'documents',doc.id))};const {data,error}=await scoped(token).storage.from('owner-documents').createSignedUrl(doc.storage_path,60,{download:doc.filename});if(error)throw error;return {doc,url:data.signedUrl}}

export async function setContractStatus(id:string,contract_status:'unsigned'|'signed',token?:string){if(local)return transaction(db=>{const p=db.properties.find(p=>p.id===id);if(!p)return null;p.contract_status=contract_status;return p});const {data,error}=await scoped(token).from('properties').update({contract_status}).eq('id',id).select('*').maybeSingle();if(error)throw error;return data}

export async function listSharedResources(token?:string):Promise<SharedResource[]>{if(local)return transaction(db=>db.sharedResources||initialResources);const {data,error}=await scoped(token).from('member_resources').select('*').order('created_at',{ascending:false});if(error)throw error;return data as SharedResource[]}
export async function addSharedResource(data:Omit<SharedResource,'id'|'file'|'format'>,bytes:Buffer){const id=randomUUID();const ext=path.extname(data.filename).toLowerCase();const record={...data,id,file:id+ext,format:ext.slice(1).toUpperCase()};const folder=path.join(root,'member-resources');await fs.mkdir(folder,{recursive:true});await fs.writeFile(path.join(folder,record.file),bytes,{mode:0o600});try{await transaction(db=>{db.sharedResources=[...(db.sharedResources||initialResources),record]})}catch(e){await fs.unlink(path.join(folder,record.file));throw e}return record}
export async function changePassword(user:User,currentPassword:string,newPassword:string,token:string){if(!local){const c=scoped();const login=await c.auth.signInWithPassword({email:user.email,password:currentPassword});if(login.error||login.data.user?.id!==user.id)throw Error('Current password incorrect');const updated=await c.auth.updateUser({password:newPassword});if(updated.error)throw updated.error;await cloud().auth.admin.signOut(token,'others');return;}await transaction(db=>{const account=db.users.find(u=>u.id===user.id);if(!account||!verifyPassword(currentPassword,account.password||''))throw Error('Current password incorrect');account.password=hashPassword(newPassword);db.sessions=db.sessions.filter(s=>s.user_id!==user.id||s.token===hashToken(token))})}
