import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const base='http://127.0.0.1:3000';const browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1050}});const page=await context.newPage();page.setDefaultTimeout(15000);const errors=[];page.on('pageerror',e=>errors.push(e.message));const routes=['/','/long-term','/co-living','/co-living/case-study','/co-living/how-it-works','/co-living/evaluate','/about','/contact','/register','/login','/portal','/portal/properties','/portal/documents','/admin'];let count=0;const tag='browser-test-'+Date.now();
try{for(const width of [1440,390]){await page.setViewportSize({width,height:950});for(const language of ['en','zh']){for(const route of routes){const response=await page.goto(base+route+'?lang='+language);assert.equal(response.status(),200,route);await page.waitForFunction(expected=>document.documentElement.lang===expected,language==='zh'?'zh-Hans':'en');await page.locator('img').evaluateAll(async images=>{await Promise.all(images.map(async image=>{if(image.loading==='lazy'){image.scrollIntoView();}await image.decode().catch(()=>{})}))});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,route+' '+language+' '+width+' overflow');assert.equal(await page.locator('img').evaluateAll(images=>images.some(i=>!i.complete||i.naturalWidth===0)),false,'broken image on '+route);count++}}}
await page.goto(base+'/?lang=en');await page.getByRole('button',{name:'Switch to Chinese',exact:true}).click();await page.waitForFunction(()=>document.documentElement.lang==='zh-Hans');assert.ok((await page.locator('h1').innerText()).includes('您的房产'));await page.locator('.visible-nav').getByRole('link',{name:'关于我们',exact:true}).click();await page.waitForURL('**/about?lang=zh');await page.waitForFunction(()=>document.documentElement.lang==='zh-Hans');assert.equal(await page.locator('html').getAttribute('lang'),'zh-Hans');
await page.goto(base+'/contact?lang=zh');await page.locator('input[name=name]').fill(tag);await page.locator('input[name=email]').fill(tag+'@example.test');await page.locator('textarea[name=message]').fill('浏览器测试：中文咨询');await page.locator('input[name=consent]').check();await page.getByRole('button',{name:'发送留言',exact:true}).click();await page.getByRole('status').filter({hasText:'已保存'}).waitFor();
await page.goto(base+'/register?lang=en');await page.locator('[name=name]').fill(tag);await page.locator('[name=email]').fill(tag+'@example.test');await page.locator('[name=password]').fill('Browser-test-password-392');await page.locator('[name=confirmPassword]').fill('Browser-test-password-392');await page.getByRole('button',{name:'Create account',exact:true}).click();await page.waitForURL('**/portal');await page.getByText('Your properties will appear here',{exact:true}).waitFor();await page.goto(base+'/co-living/evaluate?lang=en');for(const[name,value]of Object.entries({firstName:'Browser',lastName:'Test',email:tag+'@example.test',phone:'1234567890',address:'Test only',city:'Savannah',state:'GA',zip:'31401',bedrooms:'4',bathrooms:'2'}))await page.locator('[name='+name+']').fill(value);await page.locator('[name=status]').selectOption('vacant');await page.locator('[name=interest]').selectOption('co-living');await page.locator('[name=consent]').check();await page.getByRole('button',{name:'Evaluate My Property',exact:true}).click();await page.getByRole('status').filter({hasText:'saved'}).waitFor();
await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.waitForURL('**/login');
const creds=await fs.readFile('.data/LOCAL-ADMIN-LOGIN.txt','utf8');await page.locator('[name=email]').fill('agentkelly2024@gmail.com');await page.locator('[name=password]').fill(creds.match(/Password: (.+)/)[1].trim());await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL('**/admin');await page.getByText('Property & owner management',{exact:true}).waitFor();await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.waitForURL('**/login');
for(const[language,width,name]of [['en',1440,'desktop'],['zh',1440,'chinese'],['zh',390,'mobile-chinese']]){await page.setViewportSize({width,height:1050});await page.goto(base+'/?lang='+language);await page.waitForFunction(expected=>document.documentElement.lang===expected,language==='zh'?'zh-Hans':'en');await page.screenshot({path:'.data/'+name+'-final.png',fullPage:false})}
assert.deepEqual(errors,[]);console.log(JSON.stringify({routeLanguageViewportChecks:count,uiFlows:['language switching and visible navigation','Chinese contact form','English property evaluation','owner registration and logout','admin login and logout'],pageErrors:errors},null,2));
}finally{await browser.close();const db=JSON.parse(await fs.readFile('.data/store.json','utf8'));const ids=db.users.filter(u=>u.email===tag+'@example.test').map(u=>u.id);db.users=db.users.filter(u=>!ids.includes(u.id));db.sessions=db.sessions.filter(s=>!ids.includes(s.user_id));db.leads=db.leads.filter(l=>l.email!==tag+'@example.test');await fs.writeFile('.data/store.json',JSON.stringify(db,null,2))}




