import {PGlite} from '@electric-sql/pglite';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const db=new PGlite();let checks=0;
try{
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create schema storage;create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb default '{}',email_confirmed_at timestamptz);create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;grant usage on schema auth,storage,public to authenticated,anon,service_role;grant execute on function auth.uid() to authenticated;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;grant select,insert,update,delete on storage.objects to authenticated;`);
await db.exec(await fs.readFile('supabase/schema.sql','utf8'));checks++;
const a='00000000-0000-4000-8000-000000000001',b='00000000-0000-4000-8000-000000000002',admin='00000000-0000-4000-8000-000000000003',p='00000000-0000-4000-8000-000000000010';
await db.exec(`insert into auth.users(id,email,raw_user_meta_data) values('${a}','a@example.test','{"role":"admin"}'),('${b}','b@example.test','{}'),('${admin}','agentkelly2024@gmail.com','{}');`);
assert.equal((await db.query(`select role from profiles where id='${a}'`)).rows[0].role,'owner');checks++;
const promote=await fs.readFile('supabase/promote-admin.sql','utf8');await assert.rejects(()=>db.exec(promote));checks++;
await db.exec(`update auth.users set email_confirmed_at=now() where id='${admin}'`);await db.exec(promote);checks++;
await db.exec(`insert into properties(id,owner_id,title,address,strategy,status) values('${p}','${a}','A','A','undecided','review');insert into documents(owner_id,property_id,title,filename,storage_path,mime,size) values('${a}','${p}','Financial statement','a.pdf','a/file','application/pdf',10);insert into member_resources(file,filename,mime,format,title,description) values('shared/file','s.pdf','application/pdf','PDF',array['Shared','资料'],array['','']);insert into storage.objects(bucket_id,name) values('owner-documents','a/file'),('member-resources','shared/file');`);
async function as(id,fn){await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${id}',false)`);try{return await fn()}finally{await db.exec('reset role')}}
await as(a,async()=>{assert.equal((await db.query('select * from properties')).rows.length,1);assert.equal((await db.query('select * from documents')).rows.length,1);assert.equal((await db.query('select * from storage.objects')).rows.length,2);assert.equal((await db.query('select * from profiles')).rows.length,1);await db.exec(`update profiles set role='admin' where id='${a}'`);assert.equal((await db.query(`select role from profiles where id='${a}'`)).rows[0].role,'owner');await assert.rejects(()=>db.exec(`insert into properties(owner_id,title,address,strategy,status,contract_status) values('${a}','x','x','undecided','review','signed')`));await assert.rejects(()=>db.exec(`insert into properties(owner_id,title,address,strategy,status) values('${b}','x','x','undecided','review')`));await assert.rejects(()=>db.exec(`insert into storage.objects(bucket_id,name) values('member-resources','bad')`));checks+=8;});
await as(b,async()=>{assert.equal((await db.query('select * from properties')).rows.length,0);assert.equal((await db.query('select * from documents')).rows.length,0);assert.equal((await db.query("select * from storage.objects where bucket_id='owner-documents'")).rows.length,0);assert.equal((await db.query('select * from member_resources')).rows.length,1);await db.exec(`insert into properties(owner_id,title,address,strategy,status) values('${b}','B','B','undecided','review')`);checks+=5;});
await as(admin,async()=>{assert.equal((await db.query('select * from documents')).rows.length,1);await assert.rejects(()=>db.exec(`insert into documents(owner_id,property_id,title,filename,storage_path,mime,size) values('${b}','${p}','bad','b.pdf','b/file','application/pdf',10)`));checks+=2;});
await db.exec('set role anon');await assert.rejects(()=>db.query('select * from documents'));await assert.rejects(()=>db.query('select * from member_resources'));await db.exec('reset role');checks+=2;
assert.equal((await db.query('select * from storage.buckets where public=true')).rows.length,0);checks++;
console.log('PASS: '+checks+' PostgreSQL schema/RLS checks (local PGlite; hosted Supabase still needs smoke testing)');
}finally{await db.close()}
